language: node_js
node_js:
- node

install:
- npm install
- npm install -g codecov istanbul

script:
- ./node_modules/.bin/standard index.js
- istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec
- codecov
