environment:
  nodejs_version: "7"

init:
- git config --global core.autocrlf true

install:
- ps: Install-Product node $env:nodejs_version
- npm install

test_script:
- node --version
- yarn --version
- yarn test

build: off
