environment:
  nodejs_version: "18"

init:
- git config --global core.autocrlf true

install:
- ps: Install-Product node $env:nodejs_version
- npm ci

test_script:
- node --version
- npm run test

build: off
