name: Test

on: ["push", "pull_request"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        version: 10.x
    - run: npm install -g yarn

    - name: Install Dependencies
      run: yarn install
    - name: Test
      run: yarn test
    - name: Check Code Style
      run: yarn lint

    - name: Report Coverage
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
